USE chinook;  -- USE CHINOOK DB
-- JOIN PRACTICE

-- VIEW GENRE
SELECT * FROM genre; --  view album table
-- GenreId, Name

-- VIEW TRACK
SELECT * FROM track; --  view album table
-- TrackId, Name, GenreId, Composer, UnitPrice, Millseconds, Bytes

-- VIEW TRACK AND IT'S RELATED GENRE
SELECT track.Name AS TrackName, genre.Name AS GenreName, Composer, Milliseconds, Bytes, UnitPrice 
	FROM track
	LEFT JOIN genre
    ON track.GenreID =  genre.genreID;

-- VIEW TOTAL TRACKS ATTACHED TO A GENRE
SELECT genre.Name as Genre, COUNT(DISTINCT track.Name) AS TotalTracks
	FROM TRACK
    RIGHT JOIN GENRE
    ON TRACK.GENREID = GENRE.GENREID
    GROUP BY GENRE.NAME ORDER BY TotalTracks DESC;

-- VIEW CUSTOMERS
SELECT * FROM CUSTOMER; -- CUSTOMERID, FIRSTNAME, LASTNAME, COMPANY, ADDRESS, CITY, STATE, COUNTRY, EMAIL, PHONE, SUPPORTID ....

-- VIEW INVOICE
SELECT * FROM INVOICE; -- INVOICEID, CUSTOMERID, INVOICEDATE, BILLINGADDRESS, BILLINGCITY, BILLINGCOUNTRY, BILLINGPOSTALCODE, TOTAL

-- VIEW CUSTOMERS INVOICE POSTALCODE AND ADRESS DETAILS
SELECT CONCAT(UPPER(LASTNAME),', ',FIRSTNAME) AS FULL_NAME,ADDRESS, CITY, STATE, COUNTRY, EMAIL, BILLINGPOSTALCODE AS BillingPostalCode
	FROM CUSTOMER C
    INNER JOIN INVOICE I
    ON C.CUSTOMERID = I.CUSTOMERID
