USE sales_data_sample;

-- VIEW ENTIRE DATASET
SELECT * FROM sales_data_sample;
 
 -- DATA CLEANING (VIEW DUPLICATE RECORDS)
WITH CTE AS(
			SELECT *, 
					ROW_NUMBER() OVER (
						PARTITION BY ORDERNUMBER, QUANTITYORDERED,PRICEEACH
                        ORDER BY ORDERNUMBER
					) AS ROW_NUM
				FROM sales_data_sample
			)
           SELECT * FROM sales_data_sample
WHERE ORDERNUMBER IN (
    SELECT ORDERNUMBER
    FROM CTE
    WHERE ROW_NUM > 1
);
                    
 
-- GET TOTAL RECORD
SELECT COUNT(*) AS total_records FROM sales_data_sample;

-- TOTALS
SELECT COUNT(DISTINCT ORDERNUMBER) AS total_order, COUNT(DISTINCT COUNTRY) AS total_country, COUNT(DISTINCT TERRITORY)AS total_territory,
COUNT(DISTINCT CUSTOMERNAME) AS total_cutomer, COUNT(DISTINCT PRODUCTLINE) AS total_productline, FORMAT(SUM(QUANTITYORDERED),'N2') AS total_quantity,
AVG(QUANTITYORDERED) AS avg_quantity, MAX(QUANTITYORDERED) AS highest_quantity, MIN(QUANTITYORDERED) AS lowest_quantity,FORMAT(SUM(SALES),'N2') AS total_sale, 
FORMAT(AVG(SALES),'N2') AS average_sales,FORMAT(MAX(SALES),'N2')AS highest_sale, MIN(SALES) AS lowest_sale,
FORMAT((SUM(SALES)/ COUNT(DISTINCT ORDERNUMBER)),'N2') as Avg_Order_Value, -- AOV (customeer purchasing behavior)
FORMAT((COUNT(DISTINCT ORDERNUMBER)/COUNT(DISTINCT CUSTOMERNAME)),'N2') as Purcahs_Frequency -- CUSTOMER PURCAHSING FREQUENCY (customeer purchasing behavior)
FROM sales_data_sample;

-- SUM OF SALES BY TERRITOTY
SELECT TERRITORY, SUM(SALES) AS revenue FROM sales_data_sample GROUP BY TERRITORY;

-- SUM AND AVG OF PRICE BY PRODUCTLINE
SELECT PRODUCTLINE, SUM(PRICEEACH) AS total_price, AVG(PRICEEACH) AS avg_price FROM sales_data_sample GROUP BY PRODUCTLINE;

-- GET TOTAL REVENUE BY STATUS
SELECT STATUS, SUM(SALES) AS sales_by_status FROM sales_data_sample GROUP BY STATUS;

-- GET USA BASED CUSTOMERS ONLY
SELECT CUSTOMERNAME, COUNTRY, CITY FROM sales_data_sample WHERE COUNTRY = 'USA';

-- REVENUE GENERATED OVER TIME IN YEAR
SELECT YEAR_ID AS years, COUNT(DISTINCT ORDERNUMBER) AS order_count, SUM(QUANTITYORDERED) AS qantity_sold, SUM(SALES) AS total_revenue FROM sales_data_sample GROUP BY years ORDER BY years;

-- GET TOTAL SALES FOR EACH MONTH
SELECT 
-- REPRESENT MONTH IN PROPEERLY INSTEAD OF 1, 2, ..., 12 
    CASE 
        WHEN MONTH_ID = 1 THEN 'January' WHEN MONTH_ID = 2 THEN 'February' WHEN MONTH_ID = 3 THEN 'March'  WHEN MONTH_ID = 4 THEN 'April' WHEN MONTH_ID = 5 THEN 'May'
        WHEN MONTH_ID = 6 THEN 'June' WHEN MONTH_ID = 7 THEN 'July' WHEN MONTH_ID = 8 THEN 'August'WHEN MONTH_ID = 9 THEN 'September' WHEN MONTH_ID = 10 THEN 'October'
        WHEN MONTH_ID = 11 THEN 'November' WHEN MONTH_ID = 12 THEN 'December'
    END AS months,
    COUNT(*) AS order_count, SUM(SALES) AS total_revenue FROM sales_data_sample GROUP BY MONTH_ID ORDER BY total_revenue DESC;

-- GET NO OF CUSTOMERS IN EACH COUNNTRY
SELECT COUNTRY, COUNT(DISTINCT CUSTOMERNAME) AS customers FROM sales_data_sample GROUP BY COUNTRY ORDER BY customers DESC;

-- GET NO OF CITIES IN EACH COUNNTRY
SELECT COUNTRY, COUNT(DISTINCT CITY) AS cities FROM sales_data_sample GROUP BY COUNTRY ORDER BY cities DESC;

-- GET NO OF CUSTOMERS IN EACH CITY
SELECT CITY, COUNT(DISTINCT CUSTOMERNAME) AS customers FROM sales_data_sample GROUP BY CITY ORDER BY customers DESC;

-- INTEGRATING THE ABOVE THREE COMMANDS AS ONE
SELECT COUNTRY, COUNT(DISTINCT CITY) AS total_cities, COUNT(DISTINCT CUSTOMERNAME) AS total_customers FROM sales_data_sample GROUP BY COUNTRY ORDER BY total_customers DESC;

-- GET TOP PERFORMING CUSTOMERS generating over 100k
SELECT CUSTOMERNAME,  SUM(SALES) AS total_revenue FROM sales_data_sample GROUP BY CUSTOMERNAME HAVING total_revenue > 100000 ORDER BY total_revenue DESC;
-- TOP 10 CUSTOMERS
SELECT CUSTOMERNAME,  SUM(SALES) AS total_revenue FROM sales_data_sample GROUP BY CUSTOMERNAME ORDER BY total_revenue DESC LIMIT 10;

-- WHICH COUNTRY DOES THIS TOP TEN CUSTOMERS RESIDE
SELECT CUSTOMERNAME, COUNTRY,  SUM(SALES) AS total_revenue FROM sales_data_sample GROUP BY CUSTOMERNAME, COUNTRY ORDER BY total_revenue DESC LIMIT 10;

-- GET TOP PERFORMING COUNTRIES
SELECT COUNTRY, SUM(SALES) AS total_revenue FROM sales_data_sample GROUP BY COUNTRY HAVING total_revenue > 100000 ORDER BY total_revenue DESC;

-- GET TOP PERFORMING PRODUCTLINE AND DEALSIZE BY SALES
SELECT PRODUCTLINE, DEALSIZE, SUM(SALES) AS revenue FROM sales_data_sample GROUP BY PRODUCTLINE, DEALSIZE ORDER BY revenue DESC;

-- GET PURCAHSING BEHAVIOR AND AOV FOR FRANCE AND SPAIN
SELECT COUNTRY, FORMAT((SUM(SALES)/ COUNT(DISTINCT ORDERNUMBER)),'N2') as Avg_Order_Value, -- AOV (customeer purchasing behavior)
FORMAT((COUNT(DISTINCT ORDERNUMBER)/COUNT(DISTINCT CUSTOMERNAME)),'N2') as Purcahs_Frequency -- CUSTOMER PURCAHSING FREQUENCY (customeer purchasing behavior)
FROM sales_data_sample
WHERE COUNTRY IN ("SPain","France","Australia") GROUP BY COUNTRY;
